package com.example.rss

object Versions {
    const val gradle = "4.1.1"
    const val kotlin = "1.3.72"
    const val arch = "2.2.0"
    const val legacySupp = "1.0.0"
    const val appCompat = "1.1.0"
    const val coreTesting = "2.1.0"
    const val material = "1.1.0-alpha07"
    const val constraintLayout = "1.1.3"
    const val dagger = "2.28.1"
    const val okHttp = "3.8.1"
    const val gson = "2.8.6"
    const val retrofit = "2.7.1"
    const val rxJava = "2.2.16"
    const val rxAndroid = "2.1.1"
    const val stetho = "1.5.1"
    const val glide = "4.11.0"
    const val junit = "4.12"
    const val testRunner = "1.2.0"
    const val espresso = "3.2.0"
    const val mockitoKotlin = "1.6.0"
    const val lottieVersion = "3.4.0"
    const val sdp = "1.0.6"
    const val circleImageView = "3.1.0"
    const val multiDex = "2.0.1"
    const val analytics = "17.3.0"
    const val messaging = "20.1.5"
    const val crashlytics = "2.10.1"
    const val core = "17.0.1"
    const val tagManager = "17.0.0"
    const val room = "2.2.3"

}